# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. It is used to install xl
# See https://docs.brew.sh/Adding-Software-to-Homebrew

class Xl < Formula
  desc "A fast, terminal-based spreadsheet application written in Rust"
  homepage "https://github.com/only-using-ai/rustxl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/only-using-ai/rustxl/releases/download/v0.1.0/xl-macos-x86_64.tar.gz"
      sha256 "" # Update this with the actual SHA256: brew fetch --force xl
    else
      url "https://github.com/only-using-ai/rustxl/releases/download/v0.1.0/xl-macos-arm64.tar.gz"
      sha256 "" # Update this with the actual SHA256: brew fetch --force xl
    end
  end

  def install
    bin.install "xl"
  end

  test do
    # Verify that xl is installed and executable
    assert_predicate bin/"xl", :exist?
    assert_predicate bin/"xl", :executable?
  end
end
